language: node_js
node_js:
- '0.11'
- '0.10'
services:
- redis-server
deploy:
  provider: npm
  email: mail@jojow.de
  api_key:
    secure: n3gqanr8XaCdjstUEuoEa+AILH2N3dcpphXXZ+28FaOkbDt7cB1ESiJB7Lgc+pixgxivlNs+g/xG3OZ94cXFDfFphm4kZ3QYSPWNyCojlOW+VdsFDNMuZok7Qtiq1muvyQ/5iGma2sIIzKKfUO245EXffX3pnc5NkbdTgW4xa5k=
