language: node_js
node_js:
- '0.11'
- '0.10'
services:
- redis-server
deploy:
  provider: npm
  email: mail@jojow.de
  api_key:
    secure: REbBS+E3mRlu2T5QGTKEMlqwSRfwVQIlb49DJ0/Ar5xCd0W7Q96kpwCPDZk4BTAi4yWqWFY82/GWxFDIoFMzFwXZFzccZA3naoZ+T+/yQ3W8ozcKMS+gtvPFwJycaZyxGWoutpbfDZpGX2978VMK85bByX+PSZ6n5vUVgG0OZ38=
